name: skriptarnica
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0 
  go_router: ^17.0.1
  uuid: ^4.5.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/ads/ 